### ISSUE TITLE
Dose not work with PHP8.1

### ISSUE THREAD

**Issue by LMS235** [lisps/html5video#8]
Plugin dose not work with PHP8.1

**Comment by thalueng** [comment]
Put parantheses around the expressions on line 190 and line 191 in file plugins/html5video/syntax/video.php and it works in PHP 8.1. New code will read like this:
  ($w?('width="' .$w.'px" '):'').
  ($h?('height="'.$h.'px" '):'').

**Comment by peterfromearth** [comment]
@thalueng thanks
changed it, @LMS235 can you test it too and give me feedback?
